# frontend/Dockerfile

FROM node:20

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ENV NEXT_PUBLIC_API_URL=http://backend:8000/api

EXPOSE 3000

CMD ["npm", "run", "dev"]
