# Generated by Django 5.1.8 on 2025-05-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_votesubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votesubmission',
            options={'ordering': ['-id']},
        ),
    ]
