# Generated by Django 5.1.8 on 2025-05-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_alter_votesubmission_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votesubmission',
            name='choice',
            field=models.CharField(choices=[('ΝΑΙ', 'ΝΑΙ'), ('ΟΧΙ', 'ΟΧΙ'), ('ΛΕΥΚΟ', 'ΛΕΥΚΟ')], max_length=50),
        ),
    ]
