# Generated by Django 5.1.8 on 2025-05-02 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supported_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='urgentrequestlog',
            name='user_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_logs', to='user_requests.userrequest'),
        ),
    ]
