# Generated by Django 5.1.8 on 2025-04-29 04:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='supporters',
            field=models.ManyToManyField(blank=True, related_name='supported_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
