# Generated by Django 5.1.8 on 2025-04-29 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0002_userrequest_supporters'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrgentRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('supporter_count', models.PositiveIntegerField()),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_logs', to='user_requests.userrequest')),
            ],
        ),
    ]
