# Generated by Django 5.1.8 on 2025-04-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0003_urgentrequestlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='type',
            field=models.CharField(blank=True, choices=[('maintenance', 'Συντήρηση'), ('cleaning', 'Καθαριότητα'), ('technical', 'Τεχνικό'), ('other', 'Άλλο')], max_length=20, null=True),
        ),
    ]
