# Generated by Django 5.1.8 on 2025-04-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
